### ISSUE TITLE
多卡训练的问题

### ISSUE THREAD

**Issue by Zhang-echo** [ggsDing/SAM-CD#11]
想试图用多卡训练提速，修改参数后会报以下错误
……
……
900/1024 images loaded.
950/1024 images loaded.
1000/1024 images loaded.
(256, 256, 3)
1024 val images loaded.
**Segmentation fault (core dumped)**

修改了 run_encoder模块后还是报同样错误
![sam-cd1](https://github.com/ggsDing/SAM-CD/assets/56397588/e2ee9299-681d-4552-a40d-45263d86f5af)

**Comment by sijie-Xu** [comment]
I also have the same question. Have you solved it?

**Comment by Zhang-echo** [comment]
> I also have the same question. Have you solved it?

No, I'm still running the code with a single GPU, but I increased the value of the bash size.

**Comment by supoman-lei** [comment]
请问你们修改成使用GPU进行推理了吗？

**Comment by funny000** [comment]
Hi@Zhang-echo
请问你训练完效果怎么样，

**Comment by sijie-Xu** [comment]
没有实现多卡训练，那时修改内部代码太复杂，项目单卡训练效果很棒



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月16日(周四) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ggsDing/SAM-CD] 多卡训练的问题 (Issue #11)




 
***@***.***
 请问你训练完效果怎么样，

**Comment by yujia01618** [comment]
您好，我遇到了下面的问题，请问可以请教一下怎么解决吗？
Traceback (most recent call last):
  File "F:\SAM-CD-main\SAM-CD-main\train_SAM_CD.py", line 134, in <module>
    main()
  File "F:\SAM-CD-main\SAM-CD-main\train_SAM_CD.py", line 65, in main
    train(train_loader, net, optimizer, val_loader, device)
  File "F:\SAM-CD-main\SAM-CD-main\train_SAM_CD.py", line 96, in train
    outputs, outA, outB = net(imgs_A, imgs_B)
  File "D:\ProgramData\Anaconda3\envs\sam-cd\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\sam-cd\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\SAM-CD-main\SAM-CD-main\models\SAM_CD.py", line 170, in forward
    featA_s4 = self.Adapter4(featsA[3].clone())
IndexError: list index out of range
featA只有三个元素，但是代码却访问第四个，这应该怎么解决？
