### ISSUE TITLE
A Error.

### ISSUE THREAD

**Issue by Layman0527** [ggsDing/SAM-CD#4]
I can run the cd. But when i run the sam-cd model, there are some error in model. Hope your answer. I debug the code, the len(featsA) is 2.

Traceback (most recent call last):
  File "E:/code/SAM-CD-main/train_SAM_CD.py", line 202, in <module>
    main()
  File "E:/code/SAM-CD-main/train_SAM_CD.py", line 68, in main
    train(train_loader, net, optimizer, val_loader)
  File "E:/code/SAM-CD-main/train_SAM_CD.py", line 101, in train
    outputs, outA, outB = net(imgs_A, imgs_B)
  File "D:\Program Files (x86)\anaconda3\envs\SAM\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\code\SAM-CD-main\models\SAM_CD.py", line 159, in forward
    featA_s4 = self.Adapter4(featsA[3].clone())
IndexError: list index out of range

**Comment by ggsDing** [comment]
Please modify the Ultralytics source files following the instructions at:
https://github.com/ggsDing/SAM-CD/blob/main/models/FastSAM/README.md

**Comment by Layman0527** [comment]
> Please modify the Ultralytics source files following the instructions at: https://github.com/ggsDing/SAM-CD/blob/main/models/FastSAM/README.md

Thank you your help. I can run it.
